server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com

  client:
    #不向注册中心注册自己
    register-with-eureka: false
    #自己端就是注册中心,职责就是维护服务实例,并不需要检索服务
    fetch-registry: false
    service-url:
      #集群设置与Eureka Serve 交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    peer-eureka-status-refresh-time-interval-ms: 2000
    enable-self-preservation: true
